name: dmmecg
channels:
  - defaults
dependencies:
  - pip
  - python=3.10
  - pip:
    - numpy
    - torch
    - torchvision
    - timm
    - thop
    - wfdb
    - neurokit2
    - tqdm
    - seaborn
    - tensorboard
